---
title: "Multiverse_markdown"
output: html_document
date: "2025-05-7"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load the appropriate libraries
library(tidyverse)
library(readxl)
library(gitcreds)

# load the multiverse package
library(multiverse)

#load in dataframe
mv <- read_excel("multiverse_159_subjects.xlsx")

```


```{r}

#setup the variables

#Convert PSI composite index score to z score 
mv$PSI_Z <- scale(mv$PSI, center = TRUE, scale = TRUE)

#convert predictor variables (GCS, PTA, and GOAT) to z-scores. Note PTA scores have already been revered in original data to for accurate comparison between PTA, GCS, and GOAT.
mv$worst_GCS_Z <- scale(mv$worst_GCS, center = TRUE, scale = TRUE)

mv$PTA_Reverse_Z <- scale(mv$PTA_reverse, center = TRUE, scale = TRUE)

mv$GOAT_Z <- scale(mv$GOAT, center = TRUE, scale = TRUE)

#Generate a curvilinear age variable
mv$Age_Squared <- mv$age^2

#Note that race, income_ord and education variables have already been converted to ordinal.

```

```{r}

#define the multiverse object
M <- multiverse()
```


```{multiverse default-m-1, inside = M}

#add income_ord(ordinal), education (ordinal), gender

#setting up multiverse with various predictor variables using branch function for different lm models
PSI_analysis <- lm(PSI_Z ~ branch(formula,
                   "GOAT" ~ GOAT_Z,
                   "GOAT_b1" ~ GOAT_Z + race,
                   "GOAT_b2" ~ GOAT_Z + age + race,
                   "GOAT_b3" ~ GOAT_Z + race + income_ord,
                   "GOAT_w1" ~ GOAT_Z + age + Age_Squared + education + Gender,
                   "GOAT_w2" ~ GOAT_Z + age + education + Gender,
                   "GOAT_w3" ~ GOAT_Z + Age_Squared + education + Gender,
                   "PTA" ~ PTA_Reverse_Z,
                   "PTA_b1" ~ PTA_Reverse_Z + age + education + Gender,
                   "PTA_b2" ~ PTA_Reverse_Z + age + race + education + Gender,
                   "PTA_b3" ~ PTA_Reverse_Z + Age_Squared + education + Gender,
                   "PTA_w1" ~ PTA_Reverse_Z + race +income_ord,
                   "PTA_w2" ~ PTA_Reverse_Z + age + Age_Squared + income_ord,
                   "PTA_w3" ~ PTA_Reverse_Z + age + Age_Squared + income_ord,
                   "GCS" ~ worst_GCS_Z,
                   "GCS_b1" ~ worst_GCS_Z + age + race,
                   "GCS_b2" ~ worst_GCS_Z + Age_Squared + race,
                   "GCS_b3" ~ worst_GCS_Z + age + Age_Squared + race,
                   "GCS_w1" ~ worst_GCS_Z + income_ord + education + Gender,
                   "GCS_w2" ~ worst_GCS_Z + education + Gender,
                   "GCS_w3" ~ worst_GCS_Z + income_ord + Gender),
                   data = mv)

#converts the output of statistical models into a tidy data frame format for later plotting and visualization
PSI_result <- PSI_analysis |> broom::tidy(conf.int = TRUE)

```

```{r}

#execute the multiverse analysis
execute_multiverse(M)

#You can test out a specific "universe" here the various analyses contained within "PSI_analysis". Here, we can extract the nth universe. Replace n (number) with whichever university you'd like to evaluate. 
extract_variable_from_universe(M, 5, PSI_analysis) |> 
  broom::tidy()

```

```{r}

# visualize each analysis from fit in a histogram. First, load necessary libraries:
library(ggplot2)
library(dplyr)

#Here, we are visualizing the distribution of p-values.

#To filter, you can select which parts of the "universes" to plot. Here, I am excluding the covariates, which include age and race variables. 
  
  multiverse::expand(M) |>
  mutate( 
    find_results = map(.results, "PSI_result")
  ) |>
  select( find_results ) |>
  gather( "analysis", "result" ) |>
  unnest(result) |>
  filter(
    str_detect(term, "GOAT_Z|PTA_Reverse_Z|worst_GCS_Z")
  ) |>
  ggplot() +
  geom_histogram(aes(x = p.value), bins = 50, fill = "#ffffff", color = "#333333") +
  geom_vline( xintercept = 0.05, color = "red", linetype = "dashed") +
  facet_wrap(~ analysis, scales = "free", nrow = 3) +
  scale_y_continuous(
    breaks = function(x) seq(0, ceiling(max(x)), by = 1),
    limits = c(0, NA)  # Ensures y-axis starts at 0, upper limit auto-calculated
  ) +
  ggtitle("Multiverse results for PSI p-values") +
  theme_minimal() +
  theme(strip.text = element_blank()) +
  labs(x = "p-values")

  #save the histogram as a .jpg
  ggsave("PSI_pvalue_plot.jpg", 
       width = 8, height = 6, units = "in", dpi = 300)

```

```{r}

#Here, we are visualizing the distribution of beta estimates. 

#To filter, you can select which parts of the "universes" to plot. Here, I am excluding the covariates, which include age and race variables. 
  
  multiverse::expand(M) |>
  mutate( 
    find_results = map(.results, "PSI_result")
  ) |>
  select( find_results ) |>
  gather( "analysis", "result" ) |>
  unnest(result) |>
  filter(
    str_detect(term, "GOAT_Z|PTA_Reverse_Z|worst_GCS_Z")
  ) |>
  ggplot() +
  geom_histogram(aes(x = estimate), bins = 50, fill = "#ffffff", color = "#333333") +
  facet_wrap(~ analysis, scales = "free", nrow = 3) +
  ggtitle("Multiverse results for PSI beta estimates") +
  theme_minimal() +
  theme(strip.text = element_blank()) +
  labs(x = "Beta estimate") +
  scale_x_continuous(expand = expansion(mult = c(0, 0.05)))

  #save the histogram as a .jpg
  ggsave("PSI_beta_plot.jpg", 
       width = 8, height = 6, units = "in", dpi = 300)

```

```{r}

#beta visual that is animated! 

#load the necessary libraries, including animation
library(gganimate)

#Prepare data
beta_animated_visual <- multiverse::expand(M) |>
  mutate(
    find_results = map(.results, "PSI_result")
  ) |>
  unnest(cols = c(find_results)) |>
  filter(str_detect(term, "GOAT_Z|PTA_Reverse_Z|worst_GCS_Z")) |>

  
  ggplot() +
  geom_vline(xintercept = 0, colour = '#979797') +
  geom_point(aes(x = estimate, y = term)) +
  ggtitle("Multiverse results for PSI beta estimates") +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high, y = term), height = 0) +
  theme_minimal() +
  theme(axis.title.y = element_blank()) +  # Remove y-axis title
  transition_manual(.universe)

animate(beta_animated_visual, nframes = 210, fps = 1)

# Set up the file renderer to save frames as individual PNG files
frame_renderer <- file_renderer(
  dir = getwd(),           # Save to current working directory
  prefix = "beta_frame",   # Prefix for file names
  overwrite = TRUE         # Overwrite existing files if any
)

# Determine the number of unique frames (based on # of universes/ analyses)
num_frames <- beta_animated_visual$data |> 
  dplyr::pull(.universe) |> 
  unique() |> 
  length()

# Animate using the calculated number of frames
animate(
  beta_animated_visual,
  nframes = num_frames,
  fps = 4,
  renderer = gifski_renderer("beta_animation.gif")
)

```

```{r}

#testing another version
frame_renderer <- file_renderer(
  dir = "PSI",
  prefix = "frame",
  overwrite = TRUE
)
animate(
  beta_animated_visual,
  nframes = 21,
  fps = 4,
  renderer = frame_renderer,
  device = "png"
)

library(magick)

# Create list of composite frames
composite_frames <- lapply(1:7, function(i) {
  img1 <- image_read(sprintf("PSI/frame%04d.png", i))       # 0001–0007
  img2 <- image_read(sprintf("PSI/frame%04d.png", i + 7))   # 0008–0014
  img3 <- image_read(sprintf("PSI/frame%04d.png", i + 14))  # 0015–0021

  # Stack vertically (or use stack = FALSE for horizontal layout)
  image_append(c(img1, img2, img3), stack = TRUE)
})

# Animate at 2 frames per second (0.5 seconds per frame)
animation <- image_animate(image_join(composite_frames), fps = 2)

# Save as GIF
image_write(animation, "composite_beta_animation.gif")

```